/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package summercourse;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author sheha
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        ImageIcon i_mica= new ImageIcon("icons8-python-20.png");
        this.setIconImage(i_mica.getImage());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        python = new javax.swing.JRadioButton();
        opencv = new javax.swing.JRadioButton();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 50, 56), 1, true));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/small_language.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(450, 10, 450, 450);

        jPanel2.setBackground(new java.awt.Color(179, 239, 208));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(119, 120, 122), null));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Segoe Print", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(28, 46, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Enter");
        jLabel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 154, 156), new java.awt.Color(119, 120, 122), new java.awt.Color(153, 154, 156), new java.awt.Color(119, 120, 122)));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel4MouseExited(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(80, 220, 142, 30);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 2, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(28, 46, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Choose your exam");
        jLabel5.setToolTipText("");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanel2.add(jLabel5);
        jLabel5.setBounds(2, 2, 286, 28);

        python.setBackground(new java.awt.Color(179, 239, 208));
        python.setFont(new java.awt.Font("Segoe Print", 2, 14)); // NOI18N
        python.setForeground(new java.awt.Color(28, 46, 51));
        python.setText("Python");
        python.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 46, 51), 1, true));
        python.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pythonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pythonMouseExited(evt);
            }
        });
        python.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pythonActionPerformed(evt);
            }
        });
        jPanel2.add(python);
        python.setBounds(44, 78, 80, 29);

        opencv.setBackground(new java.awt.Color(179, 239, 208));
        opencv.setFont(new java.awt.Font("Segoe Print", 2, 14)); // NOI18N
        opencv.setForeground(new java.awt.Color(28, 46, 51));
        opencv.setText("Opencv");
        opencv.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(28, 46, 51), 1, true));
        opencv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                opencvMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                opencvMouseExited(evt);
            }
        });
        opencv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opencvActionPerformed(evt);
            }
        });
        jPanel2.add(opencv);
        opencv.setBounds(190, 80, 80, 29);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(logo);
        logo.setBounds(110, 120, 80, 70);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(90, 80, 290, 310);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        if(python.isSelected()){
            new PythonWeeks().setVisible(true);
            dispose();
        }else if(opencv.isSelected()){
            JOptionPane.showMessageDialog(this, "You should Finish python first");
        }        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void pythonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pythonActionPerformed
        opencv.setSelected(false);
        ImageIcon py_icon = new ImageIcon("small_python logo Bold.png");
        logo.setIcon(py_icon);

    }//GEN-LAST:event_pythonActionPerformed

    private void opencvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opencvActionPerformed
        python.setSelected(false);
        ImageIcon cv_icon = new ImageIcon("small_opencv logo.jpg");
        logo.setIcon(cv_icon);
    }//GEN-LAST:event_opencvActionPerformed

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        jLabel4.setBackground(new Color(28,46,51));
        jLabel4.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseExited
        jLabel4.setBackground(new Color(240,240,240));
        jLabel4.setForeground(new Color(28,46,51));
    }//GEN-LAST:event_jLabel4MouseExited

    private void pythonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pythonMouseEntered
        python.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_pythonMouseEntered

    private void pythonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pythonMouseExited
        python.setForeground(new Color(28,46,51));
    }//GEN-LAST:event_pythonMouseExited

    private void opencvMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opencvMouseEntered
        opencv.setForeground(new Color(0,0,0));
    }//GEN-LAST:event_opencvMouseEntered

    private void opencvMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opencvMouseExited
        opencv.setForeground(new Color(28,46,51));
    }//GEN-LAST:event_opencvMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logo;
    private javax.swing.JRadioButton opencv;
    private javax.swing.JRadioButton python;
    // End of variables declaration//GEN-END:variables
}
