/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package summercourse.Week1;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import summercourse.javaMail;

/**
 *
 * @author sheha
 */
public class Week1Exampage6 extends javax.swing.JFrame {

    /**
     * Creates new form Week1Exampage6
     */
    public Week1Exampage6() {
        initComponents();
        ImageIcon i_mica= new ImageIcon("icons8-python-20.png");
        this.setIconImage(i_mica.getImage());
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader     fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                ResultSet     rs  = s.executeQuery("Select Q11 , Q12 from Week1_Questions where id="+n+"");
                while(rs.next()){
                    String Q11= rs.getString("Q11");
                    String Q12= rs.getString("Q12");
                    if(Q11.equals("To execute a block of code repeatedly")){
                        f11.setSelected(true);
                        s11.setSelected(false);
                        th11.setSelected(false);
                }else if (Q11.equals("To convert data types")){
                        f11.setSelected(false);
                        s11.setSelected(true);
                        th11.setSelected(false);
                }else if (Q11.equals("To perform mathematical calculations")){
                        f11.setSelected(false);
                        s11.setSelected(false);
                        th11.setSelected(true);
                }   
                    if(Q12.equals("For loop")){
                        f12.setSelected(true);
                        s12.setSelected(false);
                        th12.setSelected(false);
                }else if (Q12.equals("While loop")){
                        f12.setSelected(false);
                        s12.setSelected(true);
                        th12.setSelected(false);
                }else if (Q12.equals("Do-While")){
                        f12.setSelected(false);
                        s12.setSelected(false);
                        th12.setSelected(true);
                }
                }}}catch(Exception e){
                }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        f11 = new javax.swing.JRadioButton();
        th11 = new javax.swing.JRadioButton();
        th12 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        f12 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        s11 = new javax.swing.JRadioButton();
        s12 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 50, 56));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 50, 56), 1, true));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<<< Choose >>>");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 10, 160, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 50, 56));
        jLabel2.setText("11-What is the purpose of a loop in programming?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(19, 62, 550, 21);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        f11.setBackground(new java.awt.Color(250, 250, 250));
        f11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f11.setForeground(new java.awt.Color(39, 50, 56));
        f11.setText("To execute a block of code repeatedly");
        f11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f11ActionPerformed(evt);
            }
        });
        jPanel2.add(f11);
        f11.setBounds(20, 70, 270, 23);

        th11.setBackground(new java.awt.Color(250, 250, 250));
        th11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        th11.setForeground(new java.awt.Color(39, 50, 56));
        th11.setText("To perform mathematical calculations");
        th11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th11ActionPerformed(evt);
            }
        });
        jPanel2.add(th11);
        th11.setBounds(20, 150, 260, 23);

        th12.setBackground(new java.awt.Color(250, 250, 250));
        th12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        th12.setForeground(new java.awt.Color(39, 50, 56));
        th12.setText("Do-While loop");
        th12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th12ActionPerformed(evt);
            }
        });
        jPanel2.add(th12);
        th12.setBounds(20, 320, 120, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 50, 56));
        jLabel3.setText("12-Which loop in Python is used for iterating over a sequence of elements?");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 190, 690, 21);

        f12.setBackground(new java.awt.Color(250, 250, 250));
        f12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f12.setForeground(new java.awt.Color(39, 50, 56));
        f12.setText("for loop");
        f12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f12ActionPerformed(evt);
            }
        });
        jPanel2.add(f12);
        f12.setBounds(20, 240, 80, 23);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-64.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(820, 350, 60, 50);

        s11.setBackground(new java.awt.Color(250, 250, 250));
        s11.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s11.setForeground(new java.awt.Color(39, 50, 56));
        s11.setText("To convert data types");
        s11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s11ActionPerformed(evt);
            }
        });
        jPanel2.add(s11);
        s11.setBounds(20, 110, 160, 23);

        s12.setBackground(new java.awt.Color(250, 250, 250));
        s12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s12.setForeground(new java.awt.Color(39, 50, 56));
        s12.setText("while loop");
        s12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s12ActionPerformed(evt);
            }
        });
        jPanel2.add(s12);
        s12.setBounds(20, 280, 100, 23);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-64__.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 350, 50, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 890, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void f12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f12ActionPerformed
         s12.setSelected(false);
         th12.setSelected(false);
    }//GEN-LAST:event_f12ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
            if(f11.isSelected()){
               boolean     x  = s.execute("update WEEK1_QUESTIONS set Q11='To execute a block of code repeatedly' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(s11.isSelected()){
               boolean     x2  = s.execute("update WEEK1_QUESTIONS set Q11='To convert data types' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(th11.isSelected()){
               boolean     x3  = s.execute("update WEEK1_QUESTIONS set Q11='To perform mathematical calculations' where id="+n+"");
               boolean       done = s.execute("commit");
            }
            
            if(f12.isSelected()){
               boolean     x  = s.execute("update WEEK1_QUESTIONS set Q12='For loop' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(s12.isSelected()){
               boolean     x2  = s.execute("update WEEK1_QUESTIONS set Q12='While loop' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(th12.isSelected()){
               boolean     x3  = s.execute("update WEEK1_QUESTIONS set Q12='Do-While' where id="+n+"");
               boolean       done = s.execute("commit");
            }
            }
            new Week1Exampage7().setVisible(true);
            dispose();   
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
            if(f11.isSelected()){
               boolean     x  = s.execute("update WEEK1_QUESTIONS set Q11='To execute a block of code repeatedly' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(s11.isSelected()){
               boolean     x2  = s.execute("update WEEK1_QUESTIONS set Q11='To convert data types' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(th11.isSelected()){
               boolean     x3  = s.execute("update WEEK1_QUESTIONS set Q11='To perform mathematical calculations' where id="+n+"");
               boolean       done = s.execute("commit");
            }
            
            if(f12.isSelected()){
               boolean     x  = s.execute("update WEEK1_QUESTIONS set Q12='For loop' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(s12.isSelected()){
               boolean     x2  = s.execute("update WEEK1_QUESTIONS set Q12='While loop' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(th12.isSelected()){
               boolean     x3  = s.execute("update WEEK1_QUESTIONS set Q12='Do-While' where id="+n+"");
               boolean       done = s.execute("commit");
            }
            }
            new week1Exampage5().setVisible(true);
            dispose();   
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void th11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th11ActionPerformed
         s11.setSelected(false);
         f11.setSelected(false);
    }//GEN-LAST:event_th11ActionPerformed

    private void f11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f11ActionPerformed
         s11.setSelected(false);
         th11.setSelected(false);
    }//GEN-LAST:event_f11ActionPerformed

    private void s11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s11ActionPerformed
         f11.setSelected(false);
         th11.setSelected(false);
    }//GEN-LAST:event_s11ActionPerformed

    private void s12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s12ActionPerformed
         f12.setSelected(false);
         th12.setSelected(false);
    }//GEN-LAST:event_s12ActionPerformed

    private void th12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th12ActionPerformed
         s12.setSelected(false);
         f12.setSelected(false);
    }//GEN-LAST:event_th12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Week1Exampage6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Week1Exampage6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Week1Exampage6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Week1Exampage6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Week1Exampage6().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton f11;
    private javax.swing.JRadioButton f12;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton s11;
    private javax.swing.JRadioButton s12;
    private javax.swing.JRadioButton th11;
    private javax.swing.JRadioButton th12;
    // End of variables declaration//GEN-END:variables
}
