/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package summercourse.Week1;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import summercourse.javaMail;

/**
 *
 * @author sheha
 */
public class week1Exampage5 extends javax.swing.JFrame {

    /**
     * Creates new form week1Exampage5
     */
    public week1Exampage5() {
        initComponents();
        ImageIcon i_mica= new ImageIcon("icons8-python-20.png");
        this.setIconImage(i_mica.getImage());
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader     fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                ResultSet     rs  = s.executeQuery("Select Q9 , Q10 from Week1_Questions where id="+n+"");
                while(rs.next()){
                    String Q9= rs.getString("Q9");
                    String Q10= rs.getString("Q10");
                    if(Q9.equals("3")){
                        f9.setSelected(true);
                        s9.setSelected(false);
                        th9.setSelected(false);
                }else if (Q9.equals("3.0")){
                        f9.setSelected(false);
                        s9.setSelected(true);
                        th9.setSelected(false);
                }else if (Q9.equals("4")){
                        f9.setSelected(false);
                        s9.setSelected(false);
                        th9.setSelected(true);
                }   
                    if(Q10.equals("10")){
                        f10.setSelected(true);
                        s10.setSelected(false);
                        th10.setSelected(false);
                }else if (Q10.equals("``10``")){
                        f10.setSelected(false);
                        s10.setSelected(true);
                        th10.setSelected(false);
                }else if (Q10.equals("None")){
                        f10.setSelected(false);
                        s10.setSelected(false);
                        th10.setSelected(true);
                }
                }}}catch(Exception e){
                }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        f9 = new javax.swing.JRadioButton();
        th9 = new javax.swing.JRadioButton();
        th10 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        f10 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        s9 = new javax.swing.JRadioButton();
        s10 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 50, 56));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 50, 56), 1, true));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<<< Choose >>>");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 10, 160, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 50, 56));
        jLabel2.setText("9-What is the result of the expression int(3.5)?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(19, 62, 550, 21);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        f9.setBackground(new java.awt.Color(250, 250, 250));
        f9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f9.setForeground(new java.awt.Color(39, 50, 56));
        f9.setText("3");
        f9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f9ActionPerformed(evt);
            }
        });
        jPanel2.add(f9);
        f9.setBounds(20, 70, 50, 23);

        th9.setBackground(new java.awt.Color(250, 250, 250));
        th9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        th9.setForeground(new java.awt.Color(39, 50, 56));
        th9.setText("4");
        th9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th9ActionPerformed(evt);
            }
        });
        jPanel2.add(th9);
        th9.setBounds(20, 150, 51, 23);

        th10.setBackground(new java.awt.Color(250, 250, 250));
        th10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        th10.setForeground(new java.awt.Color(39, 50, 56));
        th10.setText("None");
        th10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th10ActionPerformed(evt);
            }
        });
        jPanel2.add(th10);
        th10.setBounds(20, 320, 70, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 50, 56));
        jLabel3.setText("10-What is the result of the expression str(10)?");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 190, 570, 21);

        f10.setBackground(new java.awt.Color(250, 250, 250));
        f10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f10.setForeground(new java.awt.Color(39, 50, 56));
        f10.setText("10");
        f10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f10ActionPerformed(evt);
            }
        });
        jPanel2.add(f10);
        f10.setBounds(20, 240, 60, 23);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-64.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(820, 350, 60, 50);

        s9.setBackground(new java.awt.Color(250, 250, 250));
        s9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s9.setForeground(new java.awt.Color(39, 50, 56));
        s9.setText("3.0");
        s9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s9ActionPerformed(evt);
            }
        });
        jPanel2.add(s9);
        s9.setBounds(20, 110, 60, 23);

        s10.setBackground(new java.awt.Color(250, 250, 250));
        s10.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s10.setForeground(new java.awt.Color(39, 50, 56));
        s10.setText("\"10\"");
        s10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s10ActionPerformed(evt);
            }
        });
        jPanel2.add(s10);
        s10.setBounds(20, 280, 70, 23);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-64__.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 350, 50, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 890, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void f10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f10ActionPerformed
         s10.setSelected(false);
         th10.setSelected(false);
    }//GEN-LAST:event_f10ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
            if(f9.isSelected()){
               boolean     x  = s.execute("update WEEK1_QUESTIONS set Q9='3' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(s9.isSelected()){
               boolean     x2  = s.execute("update WEEK1_QUESTIONS set Q9='3.0' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(th9.isSelected()){
               boolean     x3  = s.execute("update WEEK1_QUESTIONS set Q9='4' where id="+n+"");
               boolean       done = s.execute("commit");
            }
            
            if(f10.isSelected()){
               boolean     x  = s.execute("update WEEK1_QUESTIONS set Q10='10' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(s10.isSelected()){
               boolean     x2  = s.execute("update WEEK1_QUESTIONS set Q10='``10``' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(th10.isSelected()){
               boolean     x3  = s.execute("update WEEK1_QUESTIONS set Q10='None' where id="+n+"");
               boolean       done = s.execute("commit");
            }
            }
            new Week1Exampage6().setVisible(true);
            dispose();   
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
            if(f9.isSelected()){
               boolean     x  = s.execute("update WEEK1_QUESTIONS set Q9='3' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(s9.isSelected()){
               boolean     x2  = s.execute("update WEEK1_QUESTIONS set Q9='3.0' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(th9.isSelected()){
               boolean     x3  = s.execute("update WEEK1_QUESTIONS set Q9='4' where id="+n+"");
               boolean       done = s.execute("commit");
            }
            
            if(f10.isSelected()){
               boolean     x  = s.execute("update WEEK1_QUESTIONS set Q10='10' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(s10.isSelected()){
               boolean     x2  = s.execute("update WEEK1_QUESTIONS set Q10='``10``' where id="+n+"");
               boolean       done = s.execute("commit");
            }else if(th10.isSelected()){
               boolean     x3  = s.execute("update WEEK1_QUESTIONS set Q10='None' where id="+n+"");
               boolean       done = s.execute("commit");
            }
            }
            new Week1Exampage4().setVisible(true);
            dispose();   
            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
        
    }//GEN-LAST:event_jLabel5MouseClicked

    private void f9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f9ActionPerformed
         s9.setSelected(false);
         th9.setSelected(false);
    }//GEN-LAST:event_f9ActionPerformed

    private void s9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s9ActionPerformed
         f9.setSelected(false);
         th9.setSelected(false);
    }//GEN-LAST:event_s9ActionPerformed

    private void th9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th9ActionPerformed
         s9.setSelected(false);
         f9.setSelected(false);
    }//GEN-LAST:event_th9ActionPerformed

    private void s10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s10ActionPerformed
         f10.setSelected(false);
         th10.setSelected(false);
    }//GEN-LAST:event_s10ActionPerformed

    private void th10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th10ActionPerformed
         s10.setSelected(false);
         f10.setSelected(false);
    }//GEN-LAST:event_th10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(week1Exampage5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(week1Exampage5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(week1Exampage5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(week1Exampage5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new week1Exampage5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton f10;
    private javax.swing.JRadioButton f9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton s10;
    private javax.swing.JRadioButton s9;
    private javax.swing.JRadioButton th10;
    private javax.swing.JRadioButton th9;
    // End of variables declaration//GEN-END:variables
}
