/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package summercourse.Week1;

import com.email.durgesh.Email;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import summercourse.javaMail;

/**
 *
 * @author sheha
 */
public class Week1Submitpage extends javax.swing.JFrame {

    /**
     * Creates new form Week1Finalpage
     */
    public Week1Submitpage() {
        initComponents();
        ImageIcon i_mica= new ImageIcon("icons8-python-20.png");
        this.setIconImage(i_mica.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 50, 56), 1, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Small_submit.jpg"))); // NOI18N

        p1.setBackground(new java.awt.Color(223, 247, 229));
        p1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 50, 56));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Submit");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(39, 50, 56), new java.awt.Color(204, 204, 204)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        p1.add(jLabel2);
        jLabel2.setBounds(0, 0, 130, 60);

        p2.setBackground(new java.awt.Color(223, 247, 229));
        p2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 50, 56));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Back");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(39, 50, 56), new java.awt.Color(204, 204, 204)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        p2.add(jLabel3);
        jLabel3.setBounds(0, 0, 130, 60);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)))
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setForeground(new Color(39,50,56));
        p2.setBackground(new Color(233,247,229));
        logo.setIcon(null);
    }//GEN-LAST:event_jLabel3MouseExited

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setForeground(new Color(233,247,229));
        p2.setBackground(new Color(39,50,56));
        ImageIcon s_icon = new ImageIcon("icons8-back-100.png");
        logo.setIcon(s_icon);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new Week1Exampage17().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setForeground(new Color(39,50,56));
        p1.setBackground(new Color(233,247,229));
        logo.setIcon(null);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setForeground(new Color(233,247,229));
        p1.setBackground(new Color(39,50,56));
        ImageIcon s_icon = new ImageIcon("icons8-done-100.png");
        logo.setIcon(s_icon);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int x=0;
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader     fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            FileWriter     fw = null;
            BufferedWriter bw = null;
            int number;
            int id    =   0 ;
            String Q1 = "no";
            String Q2 = "no";
            String Q3 = "no";
            String Q4 = "no";
            String Q5 = "no";
            String Q6 = "no";
            String Q7 = "no";
            String Q8 = "no";
            String Q9 = "no";
            String Q10 = "no";
            String Q11 = "no";
            String Q12 = "no";
            String Q13 = "no";
            String Q14 = "no";
            String Q15 = "                                   write the code here ";
            String Q16 = "                                   write the code here ";
            String Q17 = "                                   write the code here ";
            String Q18 = "                                   write the code here ";
            String Q19 = "                                   write the code here ";
            String Q20 = "                                   write the code here ";
            String Q21 = "                                   write the code here ";
            String Q22 = "                                   write the code here ";
            String Q23 = "                                   write the code here ";
            String Q24 = "                                   write the code here ";
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                ResultSet     rs  = s.executeQuery("Select * from Week1_Questions where id="+n+"");
                while(rs.next()){
                     id = rs.getInt("id");
                     Q1= rs.getString("Q1");
                     Q2= rs.getString("Q2");
                     Q3= rs.getString("Q3");
                     Q4= rs.getString("Q4");
                     Q5= rs.getString("Q5");
                     Q6= rs.getString("Q6");
                     Q7= rs.getString("Q7");
                     Q8= rs.getString("Q8");
                     Q9= rs.getString("Q9");
                     Q10= rs.getString("Q10");
                     Q11= rs.getString("Q11");
                     Q12= rs.getString("Q12");
                     Q13= rs.getString("Q13");
                     Q14= rs.getString("Q14");
                     Q15= rs.getString("Q15");
                     Q16= rs.getString("Q16");
                     Q17= rs.getString("Q17");
                     Q18= rs.getString("Q18");
                     Q15= rs.getString("Q15");
                     Q16= rs.getString("Q16");
                     Q17= rs.getString("Q17");
                     Q18= rs.getString("Q18");
                     Q19= rs.getString("Q19");
                     Q20= rs.getString("Q20");
                     Q21= rs.getString("Q21");
                     Q22= rs.getString("Q22");
                     Q23= rs.getString("Q23");
                     Q24= rs.getString("Q24");
                    }
                    }
                    if(x==0){                    
                    try{
                        
                        //  "mica2023MN@gmail.com" ---->         "xzzlgvpgdvkampzr"
                        //  "medo2023mica@gmail.com" ---->       "iiulzfizpajartio"
                        //  "hamza2023mica@gmail.com"---->       "ewamcwqbwewzqkeu"
                        //  "seif2023mica@gmail.com"---->        "cpqstvblxkhveuil"
                        //  "hassan2023mica@gmail.com"---->      "fngnythlqogromgx"
                        //  "abdelrahman2023mica@gmail.com"----> "cptqqzfhgnhxerfu"
                        //  "mohamednabil5011@gmail.com"----->   "dcnsivlscwmtzwxg"
                        //  "michael2023mica@gmail.com"---->     "ggaipdlrdicdpizj"
                        //  "abdelaziz2023mica@gmail.com"---->   "fqbiowyatlqrcign"
                        //  "ali2023mica@gmail.com"---->         "afflqfmprlbixgzq"
                        //  "homosmostafa662@gmail.com"---->     "xtxlrkjaqyhxmswp"
                        if(Q1.equals("no")||Q2.equals("no")||Q3.equals("no")||Q4.equals("no")||Q5.equals("no")||Q6.equals("no")||Q7.equals("no")||Q8.equals("no")||Q9.equals("no")||Q10.equals("no")||Q11.equals("no")||Q12.equals("no")||Q13.equals("no")||Q14.equals("no")||Q15.equals("                                   write the code here ")||Q16.equals("                                   write the code here ")||Q17.equals("                                   write the code here ")||Q18.equals("                                   write the code here ")||Q19.equals("                                   write the code here ")||Q20.equals("                                   write the code here ")||Q21.equals("                                   write the code here ")||Q22.equals("                                   write the code here ")||Q23.equals("                                   write the code here ")||Q24.equals("                                   write the code here ")){
                            new Week1Exampage1().setVisible(true);
                            dispose();
                            JOptionPane.showMessageDialog(this, "Please Complete Your Exam First Then Submit It");
                        }else{
                            if(x==0){
                            Email email= new Email("mica2023MN@gmail.com", "xzzlgvpgdvkampzr");
                            email.setFrom("Summer Course","medo2023mica@gmail.com");
                            email.setSubject("Week1 Exam");
                            email.addRecipient("mica2023MN@gmail.com");
                            if(id==1){
                                email.setContent("HAMZA MOHAMED :"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24,"text/html");
                            }else if(id==2){
                                email.setContent("SEIF ELDIN :"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24,"text/html");
                            }else if(id==3){
                                email.setContent("HASSAN HESSIN : "+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24,"text/html");
                            }else if(id==4){
                                email.setContent("ABDELRAHMAN :"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24,"text/html");
                            }else if(id==5){
                                email.setContent("MICHAEL MEDHAT :"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24,"text/html");
                            }else if(id==6){
                                email.setContent("ALI SOBHY :"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24,"text/html");
                            }else if(id==7){
                                email.setContent("ABDELAZIZ KOTB :"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24,"text/html");
                            }else if(id==12){
                                email.setContent("ADMIN :"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24,"text/html");
                            }
                            email.send();
//                            if(x==0){
//                            if(id==1){
//                                fw = new javaMail().fileWriter("ID\\Hamza.txt");
//                                bw = new javaMail().bufferedWriter(fw);
//                                bw.write("HAMZA MOHAMED :"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24);
//                            }else if(id==2){
//                                fw = new javaMail().fileWriter("ID\\Seif.txt");
//                                bw = new javaMail().bufferedWriter(fw);
//                                bw.write("SEIF ELDIN :"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24);
//                            }else if(id==3){
//                                fw = new javaMail().fileWriter("ID\\Hassan.txt");
//                                bw = new javaMail().bufferedWriter(fw);
//                                bw.write("HASSAN HESSIN : "+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24);
//                            }else if(id==4){
//                                fw = new javaMail().fileWriter("ID\\Abd EL-Rahman.txt");
//                                bw = new javaMail().bufferedWriter(fw);
//                                bw.write("ABDELRAHMAN :"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24);
//                            }else if(id==5){
//                                fw = new javaMail().fileWriter("ID\\Michael.txt");
//                                bw = new javaMail().bufferedWriter(fw);
//                                bw.write("MICHAEL MEDHAT :"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24);
//                            }else if(id==6){
//                                fw = new javaMail().fileWriter("ID\\Ali.txt");
//                                bw = new javaMail().bufferedWriter(fw);
//                                bw.write("ALI SOBHY :"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24);
//                            }else if(id==7){
//                                fw = new javaMail().fileWriter("ID\\Abd El-Aziz.txt");
//                                bw = new javaMail().bufferedWriter(fw);
//                                bw.write("ABDELAZIZ KOTB :"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24);
//                            }else if(id==12){
//                                fw = new javaMail().fileWriter("ID\\Admin.txt");
//                                bw = new javaMail().bufferedWriter(fw);
//                                bw.write("ADMIN :"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24);
//                            }
//                            bw.close();
//                            fw.close();
                            x=1;
                            new Week1Examanswer().setVisible(true);
                            dispose();
                            JOptionPane.showMessageDialog(this, "Exam Completed");
                        }           }
                    }catch(Exception e){
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "Check your Internet Connection");
                    
                  }
                }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Week1Submitpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Week1Submitpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Week1Submitpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Week1Submitpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Week1Submitpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    // End of variables declaration//GEN-END:variables
}
