/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package summercourse.Fweek;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import summercourse.javaMail;
public class FweekExampage2 extends javax.swing.JFrame {

    /**
     * Creates new form FweekExampage2
     */
    public FweekExampage2() {
        initComponents();
        ImageIcon i_mica= new ImageIcon("icons8-python-20.png");
        this.setIconImage(i_mica.getImage());
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader     fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                ResultSet     rs  = s.executeQuery("Select Q3 , Q4 from fweek_questions where id="+n+"");
                while(rs.next()){
                    String Q3= rs.getString("Q3");
                    String Q4= rs.getString("Q4");
                    if(Q3.equals("continue")){
                        f3.setSelected(true);
                        s3.setSelected(false);
                        th3.setSelected(false);
                }else if (Q3.equals("break")){
                        s3.setSelected(true);
                        f3.setSelected(false);
                        th3.setSelected(false);
                }else if (Q3.equals("out")){
                        th3.setSelected(true);
                        f3.setSelected(false);
                        s3.setSelected(false);
                }
                    if(Q4.equals("split(\",\")")){
                        f4.setSelected(true);
                        s4.setSelected(false);
                        th4.setSelected(false);
                }else if (Q4.equals("add(\",\")")){
                        s4.setSelected(true);
                        f4.setSelected(false);
                        th4.setSelected(false);
                }else if (Q4.equals("del(\",\")")){
                        th4.setSelected(true);
                        f4.setSelected(false);
                        s4.setSelected(false);
                }
                }}}catch(Exception e){
                }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        s3 = new javax.swing.JRadioButton();
        th3 = new javax.swing.JRadioButton();
        th4 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        s4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        f3 = new javax.swing.JRadioButton();
        f4 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 50, 56));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 50, 56), 1, true));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<<< Choose >>>");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 10, 160, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 50, 56));
        jLabel2.setText("3-How To continue to the next iteration of a loop ?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(19, 62, 630, 21);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        s3.setBackground(new java.awt.Color(250, 250, 250));
        s3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s3.setForeground(new java.awt.Color(39, 50, 56));
        s3.setText("break");
        s3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s3ActionPerformed(evt);
            }
        });
        jPanel2.add(s3);
        s3.setBounds(20, 90, 70, 23);

        th3.setBackground(new java.awt.Color(250, 250, 250));
        th3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        th3.setForeground(new java.awt.Color(39, 50, 56));
        th3.setText("out");
        th3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th3ActionPerformed(evt);
            }
        });
        jPanel2.add(th3);
        th3.setBounds(20, 120, 70, 23);

        th4.setBackground(new java.awt.Color(250, 250, 250));
        th4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        th4.setForeground(new java.awt.Color(39, 50, 56));
        th4.setText("del(\",\")");
        th4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th4ActionPerformed(evt);
            }
        });
        jPanel2.add(th4);
        th4.setBounds(20, 300, 110, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 50, 56));
        jLabel3.setText("4-How To make this ?  \"Hello , World\" ----->  [\"hello\", \"world\"]");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 190, 680, 21);

        s4.setBackground(new java.awt.Color(250, 250, 250));
        s4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s4.setForeground(new java.awt.Color(39, 50, 56));
        s4.setText("add(\",\")");
        s4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s4ActionPerformed(evt);
            }
        });
        jPanel2.add(s4);
        s4.setBounds(20, 270, 90, 23);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-64.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(820, 350, 60, 50);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-64__.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 350, 50, 50);

        f3.setBackground(new java.awt.Color(250, 250, 250));
        f3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f3.setForeground(new java.awt.Color(39, 50, 56));
        f3.setText("continue");
        f3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f3ActionPerformed(evt);
            }
        });
        jPanel2.add(f3);
        f3.setBounds(20, 60, 100, 23);

        f4.setBackground(new java.awt.Color(250, 250, 250));
        f4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f4.setForeground(new java.awt.Color(39, 50, 56));
        f4.setText("split(\",\")");
        f4.setActionCommand("split(\",\")");
        f4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f4ActionPerformed(evt);
            }
        });
        jPanel2.add(f4);
        f4.setBounds(20, 240, 100, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 890, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void s3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s3ActionPerformed
        s3.setSelected(true);
        f3.setSelected(false);
        th3.setSelected(false);
    }//GEN-LAST:event_s3ActionPerformed

    private void th3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th3ActionPerformed
        th3.setSelected(true);
        f3.setSelected(false);
        s3.setSelected(false);
    }//GEN-LAST:event_th3ActionPerformed

    private void th4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th4ActionPerformed
        th4.setSelected(true);
        f4.setSelected(false);
        s4.setSelected(false);
    }//GEN-LAST:event_th4ActionPerformed

    private void s4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s4ActionPerformed
        s4.setSelected(true);
        f4.setSelected(false);
        th4.setSelected(false);
    }//GEN-LAST:event_s4ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            File           file3 = new File("ID\\Q3.txt");
            FileWriter     fw3 = new FileWriter(file3);
            BufferedWriter bw3 = new BufferedWriter(fw3);
            File           file4 = new File("ID\\Q4.txt");
            FileWriter     fw4 = new FileWriter(file4);
            BufferedWriter bw4 = new BufferedWriter(fw4);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                if(f3.isSelected()){
                    bw3.write("continue");
                    boolean     x  = s.execute("update fweek_questions set Q3='continue' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(s3.isSelected()){
                    bw3.write("break");
                    boolean     x2  = s.execute("update fweek_questions set Q3='break' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(th3.isSelected()){
                    bw3.write("out");
                    boolean     x3  = s.execute("update fweek_questions set Q3='out' where id="+n+"");
                    boolean       done = s.execute("commit");
                }
                bw3.close();
                fw3.close();
                if(f4.isSelected()){
                    bw4.write("split(\",\")");
                    boolean     x  = s.execute("update fweek_questions set Q4='split(\",\")' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(s4.isSelected()){
                    bw4.write("add(\",\")");
                    boolean     x2  = s.execute("update fweek_questions set Q4='add(\",\")' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(th4.isSelected()){
                    bw4.write("del(\",\")");
                    boolean     x3  = s.execute("update fweek_questions set Q4='del(\",\")' where id="+n+"");
                    boolean       done = s.execute("commit");
                }
                bw4.close();
                fw4.close();
            }
            boolean done = s.execute("commit");
            s.close();
            c.close();
            new FweekExampage3().setVisible(true);
            dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            File           file3 = new File("ID\\Q3.txt");
            FileWriter     fw3 = new FileWriter(file3);
            BufferedWriter bw3 = new BufferedWriter(fw3);
            File           file4 = new File("ID\\Q4.txt");
            FileWriter     fw4 = new FileWriter(file4);
            BufferedWriter bw4 = new BufferedWriter(fw4);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                if(f3.isSelected()){
                    bw3.write("continue");
                    boolean     x  = s.execute("update fweek_questions set Q3='continue' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(s3.isSelected()){
                    bw3.write("break");
                    boolean     x2  = s.execute("update fweek_questions set Q3='break' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(th3.isSelected()){
                    bw3.write("out");
                    boolean     x3  = s.execute("update fweek_questions set Q3='out' where id="+n+"");
                    boolean       done = s.execute("commit");
                }
                bw3.close();
                fw3.close();
                if(f4.isSelected()){
                    bw4.write("split(\",\")");
                    boolean     x  = s.execute("update fweek_questions set Q4='split(\",\")' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(s4.isSelected()){
                    bw4.write("add(\",\")");
                    boolean     x2  = s.execute("update fweek_questions set Q4='add(\",\")' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(th4.isSelected()){
                    bw4.write("del(\",\")");
                    boolean     x3  = s.execute("update fweek_questions set Q4='del(\",\")' where id="+n+"");
                    boolean       done = s.execute("commit");
                }
                bw4.close();
                fw4.close();
            }
            boolean done = s.execute("commit");
            s.close();
            c.close();
            new FweekExampage1().setVisible(true);
            dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }

    }//GEN-LAST:event_jLabel5MouseClicked

    private void f3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f3ActionPerformed
        f3.setSelected(true);
        s3.setSelected(false);
        th3.setSelected(false);
    }//GEN-LAST:event_f3ActionPerformed

    private void f4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f4ActionPerformed
        f4.setSelected(true);
        s4.setSelected(false);
        th4.setSelected(false);
    }//GEN-LAST:event_f4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FweekExampage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FweekExampage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FweekExampage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FweekExampage2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FweekExampage2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton f3;
    public javax.swing.JRadioButton f4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JRadioButton s3;
    public javax.swing.JRadioButton s4;
    public javax.swing.JRadioButton th3;
    public javax.swing.JRadioButton th4;
    // End of variables declaration//GEN-END:variables
}
