/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package summercourse.Fweek;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import summercourse.javaMail;
public class FweekExampage10 extends javax.swing.JFrame {

    /**
     * Creates new form FweekExampage10
     */
    public FweekExampage10() {
        initComponents();
        ImageIcon i_mica= new ImageIcon("icons8-python-20.png");
        this.setIconImage(i_mica.getImage());
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader     fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                ResultSet     rs  = s.executeQuery("Select Q19 , Q20 from fweek_questions where id="+n+"");
                while(rs.next()){
                    String Q19= rs.getString("Q19");
                    String Q20= rs.getString("Q20");
                    if(Q19.equals("21")){
                        f19.setSelected(true);
                        s19.setSelected(false);
                        th19.setSelected(false);
                }else if (Q19.equals("11")){
                        s19.setSelected(true);
                        f19.setSelected(false);
                        th19.setSelected(false);
                }else if (Q19.equals("17")){
                        th19.setSelected(true);
                        f19.setSelected(false);
                        s19.setSelected(false);
                }
                    if(Q20.equals("+")){
                        f20.setSelected(true);
                        s20.setSelected(false);
                        th20.setSelected(false);
                }else if (Q20.equals("-")){
                        s20.setSelected(true);
                        f20.setSelected(false);
                        th20.setSelected(false);
                }else if (Q20.equals("|")){
                        th20.setSelected(true);
                        f20.setSelected(false);
                        s20.setSelected(false);
                }
                }}}catch(Exception e){
                }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        s19 = new javax.swing.JRadioButton();
        th19 = new javax.swing.JRadioButton();
        th20 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        s20 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        f19 = new javax.swing.JRadioButton();
        f20 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 50, 56));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 50, 56), 1, true));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<<< Choose >>>");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 10, 160, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 50, 56));
        jLabel2.setText("19-What is the result of the following expression in Python?  : 7+2*2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(19, 62, 630, 21);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        s19.setBackground(new java.awt.Color(250, 250, 250));
        s19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s19.setForeground(new java.awt.Color(39, 50, 56));
        s19.setText("11");
        s19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s19ActionPerformed(evt);
            }
        });
        jPanel2.add(s19);
        s19.setBounds(20, 100, 60, 23);

        th19.setBackground(new java.awt.Color(250, 250, 250));
        th19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        th19.setForeground(new java.awt.Color(39, 50, 56));
        th19.setText("17");
        th19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th19ActionPerformed(evt);
            }
        });
        jPanel2.add(th19);
        th19.setBounds(20, 130, 70, 23);

        th20.setBackground(new java.awt.Color(250, 250, 250));
        th20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        th20.setForeground(new java.awt.Color(39, 50, 56));
        th20.setText("|");
        th20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th20ActionPerformed(evt);
            }
        });
        jPanel2.add(th20);
        th20.setBounds(20, 310, 80, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 50, 56));
        jLabel3.setText("20-Which operator is used for string concatenation in Python?");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 190, 680, 21);

        s20.setBackground(new java.awt.Color(250, 250, 250));
        s20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s20.setForeground(new java.awt.Color(39, 50, 56));
        s20.setText("-");
        s20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s20ActionPerformed(evt);
            }
        });
        jPanel2.add(s20);
        s20.setBounds(20, 270, 70, 23);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-64.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(820, 350, 60, 50);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-64__.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 350, 50, 50);

        f19.setBackground(new java.awt.Color(250, 250, 250));
        f19.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f19.setForeground(new java.awt.Color(39, 50, 56));
        f19.setText("21");
        f19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f19ActionPerformed(evt);
            }
        });
        jPanel2.add(f19);
        f19.setBounds(20, 60, 60, 23);

        f20.setBackground(new java.awt.Color(250, 250, 250));
        f20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f20.setForeground(new java.awt.Color(39, 50, 56));
        f20.setText("+");
        f20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f20ActionPerformed(evt);
            }
        });
        jPanel2.add(f20);
        f20.setBounds(20, 230, 60, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 890, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void s19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s19ActionPerformed
        s19.setSelected(true);
        f19.setSelected(false);
        th19.setSelected(false);
    }//GEN-LAST:event_s19ActionPerformed

    private void th19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th19ActionPerformed
        th19.setSelected(true);
        f19.setSelected(false);
        s19.setSelected(false);
    }//GEN-LAST:event_th19ActionPerformed

    private void th20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th20ActionPerformed
        th20.setSelected(true);
        f20.setSelected(false);
        s20.setSelected(false);
    }//GEN-LAST:event_th20ActionPerformed

    private void s20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s20ActionPerformed
        s20.setSelected(true);
        f20.setSelected(false);
        th20.setSelected(false);
    }//GEN-LAST:event_s20ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            File           file19 = new File("ID\\Q19.txt");
            FileWriter     fw19 = new FileWriter(file19);
            BufferedWriter bw19 = new BufferedWriter(fw19);
            File           file20 = new File("ID\\Q20.txt");
            FileWriter     fw20 = new FileWriter(file20);
            BufferedWriter bw20 = new BufferedWriter(fw20);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                if(f19.isSelected()){
                    bw19.write("21");
                    boolean     x  = s.execute("update fweek_questions set Q19='21' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(s19.isSelected()){
                    bw19.write("11");
                    boolean     x2  = s.execute("update fweek_questions set Q19='11' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(th19.isSelected()){
                    bw19.write("17");
                    boolean     x19  = s.execute("update fweek_questions set Q19='17' where id="+n+"");
                    boolean       done = s.execute("commit");
                }
                bw19.close();
                fw19.close();
                if(f20.isSelected()){
                    bw20.write("+");
                    boolean     x  = s.execute("update fweek_questions set Q20='+' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(s20.isSelected()){
                    bw20.write("-");
                    boolean     x2  = s.execute("update fweek_questions set Q20='-' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(th20.isSelected()){
                    bw20.write("|");
                    boolean     x3  = s.execute("update fweek_questions set Q20='|' where id="+n+"");
                    boolean       done = s.execute("commit");
                }
                bw20.close();
                fw20.close();
            }
            boolean done = s.execute("commit");
            s.close();
            c.close();
            new FweekExampage11().setVisible(true);
            dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            File           file19 = new File("ID\\Q19.txt");
            FileWriter     fw19 = new FileWriter(file19);
            BufferedWriter bw19 = new BufferedWriter(fw19);
            File           file20 = new File("ID\\Q20.txt");
            FileWriter     fw20 = new FileWriter(file20);
            BufferedWriter bw20 = new BufferedWriter(fw20);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                if(f19.isSelected()){
                    bw19.write("21");
                    boolean     x  = s.execute("update fweek_questions set Q19='21' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(s19.isSelected()){
                    bw19.write("11");
                    boolean     x2  = s.execute("update fweek_questions set Q19='11' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(th19.isSelected()){
                    bw19.write("17");
                    boolean     x19  = s.execute("update fweek_questions set Q19='17' where id="+n+"");
                    boolean       done = s.execute("commit");
                }
                bw19.close();
                fw19.close();
                if(f20.isSelected()){
                    bw20.write("+");
                    boolean     x  = s.execute("update fweek_questions set Q20='+' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(s20.isSelected()){
                    bw20.write("-");
                    boolean     x2  = s.execute("update fweek_questions set Q20='-' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(th20.isSelected()){
                    bw20.write("|");
                    boolean     x3  = s.execute("update fweek_questions set Q20='|' where id="+n+"");
                    boolean       done = s.execute("commit");
                }
                bw20.close();
                fw20.close();
            }
            boolean done = s.execute("commit");
            s.close();
            c.close();
            new FweekExampage9().setVisible(true);
            dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
          
    }//GEN-LAST:event_jLabel5MouseClicked

    private void f19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f19ActionPerformed
        f19.setSelected(true);
        s19.setSelected(false);
        th19.setSelected(false);
    }//GEN-LAST:event_f19ActionPerformed

    private void f20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f20ActionPerformed
        f20.setSelected(true);
        s20.setSelected(false);
        th20.setSelected(false);
    }//GEN-LAST:event_f20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FweekExampage10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FweekExampage10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FweekExampage10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FweekExampage10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FweekExampage10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton f19;
    public javax.swing.JRadioButton f20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JRadioButton s19;
    public javax.swing.JRadioButton s20;
    public javax.swing.JRadioButton th19;
    public javax.swing.JRadioButton th20;
    // End of variables declaration//GEN-END:variables
}
