/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package summercourse.Fweek;
import java.awt.Color;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import summercourse.javaMail;
public class FweekSubmitpage extends javax.swing.JFrame {

    /**
     * Creates new form FweekSubmitpage
     */
    public FweekSubmitpage() {
        initComponents();
        ImageIcon i_mica= new ImageIcon("icons8-python-20.png");
        this.setIconImage(i_mica.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        p1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 50, 56), 1, true));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Small_submit.jpg"))); // NOI18N

        p1.setBackground(new java.awt.Color(223, 247, 229));
        p1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 50, 56));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Submit");
        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(39, 50, 56), new java.awt.Color(204, 204, 204)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
        });
        p1.add(jLabel2);
        jLabel2.setBounds(0, 0, 130, 60);

        p2.setBackground(new java.awt.Color(223, 247, 229));
        p2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Emoji", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 50, 56));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Back");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(39, 50, 56), new java.awt.Color(204, 204, 204)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        p2.add(jLabel3);
        jLabel3.setBounds(0, 0, 130, 60);

        logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(118, 118, 118)))
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(p1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(p2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        int x=0;
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader     fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            String         full = "ID\\All_Answer.txt";
            FileWriter     fw = new javaMail().fileWriter(full);
            BufferedWriter bw = new javaMail().bufferedWriter(fw);
            int number;
            String Q1 = null;
            String Q2 = null;
            String Q3 = null;
            String Q4 = null;
            String Q5 = null;
            String Q6 = null;
            String Q7 = null;
            String Q8 = null;
            String Q9 = null;
            String Q10 = null;
            String Q11 = null;
            String Q12 = null;
            String Q13 = null;
            String Q14 = null;
            String Q15 = null;
            String Q16 = null;
            String Q17 = null;
            String Q18 = null;
            String Q19 = null;
            String Q20 = null;
            String Q21 = null;
            String Q22 = null;
            String Q23 = null;
            String Q24 = null;
            String Q25 = null;
            String Q26 = null;
            String Q27 = null;
            String Q28 = null;
            String Q29 = null;
            String Q30 = null;
            String Q31 = null;
            String Q32 = null;
            String Q33 = null;
            String Q34 = null;
            String Q35 = null;
            String Q36 = null;
            String Q37 = null;
            String Q38 = null;
            String Q39 = null;
            String Q40 = null;
            int    id  = 0;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                ResultSet     rs  = s.executeQuery("Select * from fweek_questions where id="+n+"");
                while(rs.next()){
                    id = rs.getInt("id");
                    Q1= rs.getString("Q1");
                    Q2= rs.getString("Q2");
                    Q3= rs.getString("Q3");
                    Q4= rs.getString("Q4");
                    Q5= rs.getString("Q5");
                    Q6= rs.getString("Q6");
                    Q7= rs.getString("Q7");
                    Q8= rs.getString("Q8");
                    Q9= rs.getString("Q9");
                    Q10= rs.getString("Q10");
                    Q11= rs.getString("Q11");
                    Q12= rs.getString("Q12");
                    Q13= rs.getString("Q13");
                    Q14= rs.getString("Q14");
                    Q15= rs.getString("Q15");
                    Q16= rs.getString("Q16");
                    Q17= rs.getString("Q17");
                    Q18= rs.getString("Q18");
                    Q19= rs.getString("Q19");
                    Q20= rs.getString("Q20");
                    Q21= rs.getString("Q21");
                    Q22= rs.getString("Q22");
                    Q23= rs.getString("Q23");
                    Q24= rs.getString("Q24");
                    Q25= rs.getString("Q25");
                    Q26= rs.getString("Q26");
                    Q27= rs.getString("Q27");
                    Q28= rs.getString("Q28");
                    Q29= rs.getString("Q29");
                    Q30= rs.getString("Q30");
                    Q31= rs.getString("Q31");
                    Q32= rs.getString("Q32");
                    Q33= rs.getString("Q33");
                    Q34= rs.getString("Q34");
                    Q35= rs.getString("Q35");
                    Q36= rs.getString("Q36");
                    Q37= rs.getString("Q37");
                    Q38= rs.getString("Q38");
                    Q39= rs.getString("Q39");
                    Q40= rs.getString("Q40");
                }
            }

            try{
                //  "mica2023MN@gmail.com" ---->         "xzzlgvpgdvkampzr"
                //  "medo2023mica@gmail.com" ---->       "iiulzfizpajartio"
                //  "hamza2023mica@gmail.com"---->       "ewamcwqbwewzqkeu"
                //  "seif2023mica@gmail.com"---->        "cpqstvblxkhveuil"
                //  "hassan2023mica@gmail.com"---->      "fngnythlqogromgx"
                //  "abdelrahman2023mica@gmail.com"----> "cptqqzfhgnhxerfu"
                //  "mohamednabil5011@gmail.com"----->   "dcnsivlscwmtzwxg"
                //  "michael2023mica@gmail.com"---->     "ggaipdlrdicdpizj"
                //  "abdelaziz2023mica@gmail.com"---->   "fqbiowyatlqrcign"
                //  "ali2023mica@gmail.com"---->         "afflqfmprlbixgzq"
                //  "homosmostafa662@gmail.com"---->     "xtxlrkjaqyhxmswp"
                if(Q1.equals("no")||Q2.equals("no")||Q3.equals("no")||Q4.equals("no")||Q5.equals("no")||Q6.equals("no")||Q7.equals("no")||Q8.equals("no")||Q9.equals("no")||Q10.equals("no")||Q11.equals("no")||Q12.equals("no")||Q13.equals("no")||Q14.equals("no")||Q15.equals("no")||Q16.equals("no")||Q17.equals("no")||Q18.equals("no")||Q19.equals("no")||Q20.equals("no")||Q21.equals("no")||Q22.equals("no")||Q23.equals("no")||Q24.equals("no")||Q25.equals("                                   write the code here ")||Q26.equals("                                   write the code here ")||Q27.equals("                                   write the code here ")||Q28.equals("                                   write the code here ")||Q29.equals("                                   write the code here ")||Q30.equals("                                   write the code here ")||Q31.equals("                                   write the code here ")||Q32.equals("                                   write the code here ")||Q33.equals("                                   write the code here ")||Q34.equals("                                   write the code here ")||Q35.equals("                                   write the code here ")||Q36.equals("                                   write the code here ")||Q37.equals("                                   write the code here ")||Q38.equals("                                   write the code here ")||Q39.equals("                                   write the code here ")||Q40.equals("                                   write the code here ")){
                    new FweekExampage1().setVisible(true);
                    dispose();
                    JOptionPane.showMessageDialog(this, "Please Complete Your Exam First Then Submit It");
                }else{
                    if(x==0){
                                      if(id==1){
                                          bw.write("Hamza"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24+"\n"+" Q25= "+Q25+"\n"+" Q26= "+Q26+"\n"+" Q27= "+Q27+"\n"+" Q28= "+Q28+"\n"+" Q29= "+Q29+"\n"+" Q30= "+Q30+"\n"+" Q31= "+Q31+"\n"+" Q32= "+Q32+"\n"+" Q33= "+Q33+"\n"+" Q34= "+Q34+"\n"+" Q35= "+Q35+"\n"+" Q36= "+Q36+"\n"+" Q37= "+Q37+"\n"+" Q38= "+Q38+"\n"+" Q39= "+Q39+"\n"+" Q40= "+Q40);
                                      }else if(id==2){
                                          bw.write("Seif"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24+"\n"+" Q25= "+Q25+"\n"+" Q26= "+Q26+"\n"+" Q27= "+Q27+"\n"+" Q28= "+Q28+"\n"+" Q29= "+Q29+"\n"+" Q30= "+Q30+"\n"+" Q31= "+Q31+"\n"+" Q32= "+Q32+"\n"+" Q33= "+Q33+"\n"+" Q34= "+Q34+"\n"+" Q35= "+Q35+"\n"+" Q36= "+Q36+"\n"+" Q37= "+Q37+"\n"+" Q38= "+Q38+"\n"+" Q39= "+Q39+"\n"+" Q40= "+Q40);
                                      }else if(id==3){
                                          bw.write("Hassan"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24+"\n"+" Q25= "+Q25+"\n"+" Q26= "+Q26+"\n"+" Q27= "+Q27+"\n"+" Q28= "+Q28+"\n"+" Q29= "+Q29+"\n"+" Q30= "+Q30+"\n"+" Q31= "+Q31+"\n"+" Q32= "+Q32+"\n"+" Q33= "+Q33+"\n"+" Q34= "+Q34+"\n"+" Q35= "+Q35+"\n"+" Q36= "+Q36+"\n"+" Q37= "+Q37+"\n"+" Q38= "+Q38+"\n"+" Q39= "+Q39+"\n"+" Q40= "+Q40);
                                      }else if(id==4){
                                          bw.write("Abd El-Rahman"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24+"\n"+" Q25= "+Q25+"\n"+" Q26= "+Q26+"\n"+" Q27= "+Q27+"\n"+" Q28= "+Q28+"\n"+" Q29= "+Q29+"\n"+" Q30= "+Q30+"\n"+" Q31= "+Q31+"\n"+" Q32= "+Q32+"\n"+" Q33= "+Q33+"\n"+" Q34= "+Q34+"\n"+" Q35= "+Q35+"\n"+" Q36= "+Q36+"\n"+" Q37= "+Q37+"\n"+" Q38= "+Q38+"\n"+" Q39= "+Q39+"\n"+" Q40= "+Q40);
                                      }else if(id==5){
                                          bw.write("Michael"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24+"\n"+" Q25= "+Q25+"\n"+" Q26= "+Q26+"\n"+" Q27= "+Q27+"\n"+" Q28= "+Q28+"\n"+" Q29= "+Q29+"\n"+" Q30= "+Q30+"\n"+" Q31= "+Q31+"\n"+" Q32= "+Q32+"\n"+" Q33= "+Q33+"\n"+" Q34= "+Q34+"\n"+" Q35= "+Q35+"\n"+" Q36= "+Q36+"\n"+" Q37= "+Q37+"\n"+" Q38= "+Q38+"\n"+" Q39= "+Q39+"\n"+" Q40= "+Q40);
                                      }else if(id==6){
                                          bw.write("Ali"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24+"\n"+" Q25= "+Q25+"\n"+" Q26= "+Q26+"\n"+" Q27= "+Q27+"\n"+" Q28= "+Q28+"\n"+" Q29= "+Q29+"\n"+" Q30= "+Q30+"\n"+" Q31= "+Q31+"\n"+" Q32= "+Q32+"\n"+" Q33= "+Q33+"\n"+" Q34= "+Q34+"\n"+" Q35= "+Q35+"\n"+" Q36= "+Q36+"\n"+" Q37= "+Q37+"\n"+" Q38= "+Q38+"\n"+" Q39= "+Q39+"\n"+" Q40= "+Q40);
                                      }else if(id==7){
                                          bw.write("Abd El-Aziz"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24+"\n"+" Q25= "+Q25+"\n"+" Q26= "+Q26+"\n"+" Q27= "+Q27+"\n"+" Q28= "+Q28+"\n"+" Q29= "+Q29+"\n"+" Q30= "+Q30+"\n"+" Q31= "+Q31+"\n"+" Q32= "+Q32+"\n"+" Q33= "+Q33+"\n"+" Q34= "+Q34+"\n"+" Q35= "+Q35+"\n"+" Q36= "+Q36+"\n"+" Q37= "+Q37+"\n"+" Q38= "+Q38+"\n"+" Q39= "+Q39+"\n"+" Q40= "+Q40);
                                      }else if(id==12){
                                          bw.write("admin"+"\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24+"\n"+" Q25= "+Q25+"\n"+" Q26= "+Q26+"\n"+" Q27= "+Q27+"\n"+" Q28= "+Q28+"\n"+" Q29= "+Q29+"\n"+" Q30= "+Q30+"\n"+" Q31= "+Q31+"\n"+" Q32= "+Q32+"\n"+" Q33= "+Q33+"\n"+" Q34= "+Q34+"\n"+" Q35= "+Q35+"\n"+" Q36= "+Q36+"\n"+" Q37= "+Q37+"\n"+" Q38= "+Q38+"\n"+" Q39= "+Q39+"\n"+" Q40= "+Q40);
                                      }
//                        final String fromEmail = "medo2023mica@gmail.com";//user.getFromEmail(); //requires valid gmail id
//                        final String password = "iiulzfizpajartio";//user.getPassword(); // correct password for gmail id
//                        final String toEmail = "mica2023mn@gmail.com"; // can be any email id
//
//                        Properties props = new Properties();
//                        props.put("mail.smtp.host", "smtp.gmail.com"); //SMTP Host
//                        props.put("mail.smtp.port", "587"); //TLS Port
//                        props.put("mail.smtp.auth", "true"); //enable authentication
//                        props.put("mail.smtp.starttls.enable", "true"); //enable STARTTLS
//                        Session session = Session.getDefaultInstance(props,null);
//                        MimeMessage msg = new MimeMessage(session);
//                        //set message headers
//                        msg.addHeader("Content-type", "text/HTML; charset=UTF-8");
//                        msg.addHeader("format", "flowed");
//                        msg.addHeader("Content-Transfer-Encoding", "8bit");
//                        msg.setReplyTo(InternetAddress.parse(fromEmail, false));
//                        msg.setSubject("Week2", "UTF-8");
//                        if(id==1){
//                            msg.setFrom(new InternetAddress(fromEmail, "HAMZA MOHAMED"));
//                            msg.setText("\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24+"\n"+" Q25= "+Q25,"UTF-8");
//                        }else if(id==2){
//                            msg.setFrom(new InternetAddress(fromEmail, "SEIF ELDIN"));
//                            msg.setText("\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24+"\n"+" Q25= "+Q25,"UTF-8");
//                        }else if(id==3){
//                            msg.setFrom(new InternetAddress(fromEmail, "HASSAN HESSIN"));
//                            msg.setText("\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24+"\n"+" Q25= "+Q25,"UTF-8");
//                        }else if(id==4){
//                            msg.setFrom(new InternetAddress(fromEmail, "ABDELRAHMAN"));
//                            msg.setText("\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24+"\n"+" Q25= "+Q25,"UTF-8");
//                        }else if(id==5){
//                            msg.setFrom(new InternetAddress(fromEmail, "MICHAEL MEDHAT"));
//                            msg.setText("\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24+"\n"+" Q25= "+Q25,"UTF-8");
//                        }else if(id==6){
//                            msg.setFrom(new InternetAddress(fromEmail, "ALI SOBHY"));
//                            msg.setText("\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24,"UTF-8");
//                        }else if(id==7){
//                            msg.setFrom(new InternetAddress(fromEmail, "ABDELAZIZ KOTB"));
//                            msg.setText("\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24,"UTF-8");
//                        }else if(id==12){
//                            msg.setFrom(new InternetAddress(fromEmail, "ADMIN"));
//                            msg.setText("\n"+" Q1= "+Q1+"\n"+" Q2= "+Q2+"\n"+" Q3= "+Q3+"\n"+" Q4= "+Q4+"\n"+" Q5= "+Q5+"\n"+" Q6= "+Q6+"\n"+" Q7= "+Q7+"\n"+" Q8= "+Q8+"\n"+" Q9= "+Q9+"\n"+" Q10= "+Q10+"\n"+" Q11= "+Q11+"\n"+" Q12= "+Q12+"\n"+" Q13= "+Q13+"\n"+" Q14= "+Q14+"\n"+" Q15= "+Q15+"\n"+" Q16= "+Q16+"\n"+" Q17= "+Q17+"\n"+" Q18= "+Q18+"\n"+" Q19= "+Q19+"\n"+" Q20= "+Q20+"\n"+" Q21= "+Q21+"\n"+" Q22= "+Q22+"\n"+" Q23= "+Q23+"\n"+" Q24= "+Q24,"UTF-8");
//                        }
//                        msg.setSentDate(new Date());
//                        msg.setRecipients(Message.RecipientType.TO, InternetAddress.parse(toEmail, false));
//                        System.out.println("Message is ready");
//                        Transport trans=session.getTransport("smtp");
//                        trans.connect("smtp.gmail.com",fromEmail,password);
//                        trans.sendMessage(msg,msg.getAllRecipients());
//                        System.out.println("EMail Sent Successfully!!");
                                                    bw.close();
                                                    fw.close();
                        new summercourse.Main().setVisible(true);
                        dispose();
                        JOptionPane.showMessageDialog(this, "Exam Completed");

                    }}

                }catch(Exception e){
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, e.getMessage());

                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        jLabel2.setForeground(new Color(233,247,229));
        p1.setBackground(new Color(39,50,56));
        ImageIcon s_icon = new ImageIcon("icons8-done-100.png");
        logo.setIcon(s_icon);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        jLabel2.setForeground(new Color(39,50,56));
        p1.setBackground(new Color(233,247,229));
        logo.setIcon(null);
    }//GEN-LAST:event_jLabel2MouseExited

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        new FweekExampage28().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        jLabel3.setForeground(new Color(233,247,229));
        p2.setBackground(new Color(39,50,56));
        ImageIcon s_icon = new ImageIcon("icons8-back-100.png");
        logo.setIcon(s_icon);
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        jLabel3.setForeground(new Color(39,50,56));
        p2.setBackground(new Color(233,247,229));
        logo.setIcon(null);
    }//GEN-LAST:event_jLabel3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FweekSubmitpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FweekSubmitpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FweekSubmitpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FweekSubmitpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FweekSubmitpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    // End of variables declaration//GEN-END:variables
}
