/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package summercourse.Fweek;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import summercourse.javaMail;
public class FweekExampage9 extends javax.swing.JFrame {

    /**
     * Creates new form FweekExampage9
     */
    public FweekExampage9() {
        initComponents();
        ImageIcon i_mica= new ImageIcon("icons8-python-20.png");
        this.setIconImage(i_mica.getImage());
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader     fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                ResultSet     rs  = s.executeQuery("Select Q17 , Q18 from fweek_questions where id="+n+"");
                while(rs.next()){
                    String Q17= rs.getString("Q17");
                    String Q18= rs.getString("Q18");
                    if(Q17.equals("Jo")){
                        f17.setSelected(true);
                        s17.setSelected(false);
                        th17.setSelected(false);
                }else if (Q17.equals("oh")){
                        s17.setSelected(true);
                        f17.setSelected(false);
                        th17.setSelected(false);
                }else if (Q17.equals("Joh")){
                        th17.setSelected(true);
                        f17.setSelected(false);
                        s17.setSelected(false);
                }
                    if(Q18.equals("-1")){
                        f18.setSelected(true);
                        s18.setSelected(false);
                        th18.setSelected(false);
                }else if (Q18.equals("False")){
                        s18.setSelected(true);
                        f18.setSelected(false);
                        th18.setSelected(false);
                }else if (Q18.equals("Error")){
                        th18.setSelected(true);
                        f18.setSelected(false);
                        s18.setSelected(false);
                }
                }}}catch(Exception e){
                }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        th17 = new javax.swing.JRadioButton();
        f17 = new javax.swing.JRadioButton();
        th18 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        f18 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        s17 = new javax.swing.JRadioButton();
        s18 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 50, 56));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 50, 56), 1, true));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<<< Choose >>>");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 10, 160, 30);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        th17.setBackground(new java.awt.Color(250, 250, 250));
        th17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        th17.setForeground(new java.awt.Color(39, 50, 56));
        th17.setText("Joh");
        th17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th17ActionPerformed(evt);
            }
        });
        jPanel2.add(th17);
        th17.setBounds(20, 170, 200, 20);

        f17.setBackground(new java.awt.Color(250, 250, 250));
        f17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f17.setForeground(new java.awt.Color(39, 50, 56));
        f17.setText("Jo");
        f17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f17ActionPerformed(evt);
            }
        });
        jPanel2.add(f17);
        f17.setBounds(20, 110, 140, 20);

        th18.setBackground(new java.awt.Color(250, 250, 250));
        th18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        th18.setForeground(new java.awt.Color(39, 50, 56));
        th18.setText("Error");
        th18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th18ActionPerformed(evt);
            }
        });
        jPanel2.add(th18);
        th18.setBounds(20, 320, 150, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 50, 56));
        jLabel3.setText("17-What is the result of the following code?");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 20, 470, 20);

        f18.setBackground(new java.awt.Color(250, 250, 250));
        f18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f18.setForeground(new java.awt.Color(39, 50, 56));
        f18.setText("-1");
        f18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f18ActionPerformed(evt);
            }
        });
        jPanel2.add(f18);
        f18.setBounds(20, 240, 150, 23);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-64.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(820, 350, 60, 50);

        s17.setBackground(new java.awt.Color(250, 250, 250));
        s17.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s17.setForeground(new java.awt.Color(39, 50, 56));
        s17.setText("oh");
        s17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s17ActionPerformed(evt);
            }
        });
        jPanel2.add(s17);
        s17.setBounds(20, 140, 180, 20);

        s18.setBackground(new java.awt.Color(250, 250, 250));
        s18.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s18.setForeground(new java.awt.Color(39, 50, 56));
        s18.setText("False");
        s18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s18ActionPerformed(evt);
            }
        });
        jPanel2.add(s18);
        s18.setBounds(20, 280, 150, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(39, 50, 56));
        jLabel6.setText("18-What does the find() method return if the substring is not found in a string?");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 200, 730, 21);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-64__.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 350, 50, 50);

        jLabel7.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(39, 50, 56));
        jLabel7.setText("print(line[1:3])");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(120, 80, 130, 21);

        jLabel8.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(39, 50, 56));
        jLabel8.setText("line=\"John\"");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(120, 50, 190, 21);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 890, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void th17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th17ActionPerformed
        s17.setSelected(false);
        f17.setSelected(false);
    }//GEN-LAST:event_th17ActionPerformed

    private void f17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f17ActionPerformed
        s17.setSelected(false);
        th17.setSelected(false);
    }//GEN-LAST:event_f17ActionPerformed

    private void th18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th18ActionPerformed
        s18.setSelected(false);
        f18.setSelected(false);
    }//GEN-LAST:event_th18ActionPerformed

    private void f18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f18ActionPerformed
        s18.setSelected(false);
        th18.setSelected(false);
    }//GEN-LAST:event_f18ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            int number;
            File           file17 = new File("ID\\Q17.txt");
            FileWriter     fw17 = new FileWriter(file17);
            BufferedWriter bw17 = new BufferedWriter(fw17);
            File           file18 = new File("ID\\Q18.txt");
            FileWriter     fw18 = new FileWriter(file18);
            BufferedWriter bw18 = new BufferedWriter(fw18);
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                if(f17.isSelected()){
                    boolean     x  = s.execute("update fweek_questions set Q17='Jo' where id="+n+"");
                    bw17.write("Jo");
                }else if(s17.isSelected()){
                    boolean     x2  = s.execute("update fweek_questions set Q17='oh' where id="+n+"");
                    bw17.write("oh");
                }else if(th17.isSelected()){
                    boolean     x3  = s.execute("update fweek_questions set Q17='Joh' where id="+n+"");
                    bw17.write("Joh");
                }
                bw17.close();
                fw17.close();
                if(f18.isSelected()){
                    boolean     x  = s.execute("update fweek_questions set Q18='-1' where id="+n+"");
                    bw18.write("-1");
                }else if(s18.isSelected()){
                    boolean     x2  = s.execute("update fweek_questions set Q18='False' where id="+n+"");
                    bw18.write("False");
                }else if(th18.isSelected()){
                    boolean     x3  = s.execute("update fweek_questions set Q18='Error' where id="+n+"");
                    bw18.write("Error");
                }
                bw18.close();
                fw18.close();
            }
            boolean       done = s.execute("commit");
            s.close();
            c.close();
            new FweekExampage10().setVisible(true);
            dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void s17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s17ActionPerformed
        f17.setSelected(false);
        th17.setSelected(false);
    }//GEN-LAST:event_s17ActionPerformed

    private void s18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s18ActionPerformed
        f18.setSelected(false);
        th18.setSelected(false);
    }//GEN-LAST:event_s18ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            int number;
            File           file17 = new File("ID\\Q17.txt");
            FileWriter     fw17 = new FileWriter(file17);
            BufferedWriter bw17 = new BufferedWriter(fw17);
            File           file18 = new File("ID\\Q18.txt");
            FileWriter     fw18 = new FileWriter(file18);
            BufferedWriter bw18 = new BufferedWriter(fw18);
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                if(f17.isSelected()){
                    boolean     x  = s.execute("update fweek_questions set Q17='Jo' where id="+n+"");
                    bw17.write("Jo");
                }else if(s17.isSelected()){
                    boolean     x2  = s.execute("update fweek_questions set Q17='oh' where id="+n+"");
                    bw17.write("oh");
                }else if(th17.isSelected()){
                    boolean     x3  = s.execute("update fweek_questions set Q17='Joh' where id="+n+"");
                    bw17.write("Joh");
                }
                bw17.close();
                fw17.close();
                if(f18.isSelected()){
                    boolean     x  = s.execute("update fweek_questions set Q18='-1' where id="+n+"");
                    bw18.write("-1");
                }else if(s18.isSelected()){
                    boolean     x2  = s.execute("update fweek_questions set Q18='False' where id="+n+"");
                    bw18.write("False");
                }else if(th18.isSelected()){
                    boolean     x3  = s.execute("update fweek_questions set Q18='Error' where id="+n+"");
                    bw18.write("Error");
                }
                bw18.close();
                fw18.close();
            }
            boolean       done = s.execute("commit");
            s.close();
            c.close();
            new FweekExampage8().setVisible(true);
            dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }

    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FweekExampage9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FweekExampage9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FweekExampage9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FweekExampage9.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FweekExampage9().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton f17;
    private javax.swing.JRadioButton f18;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton s17;
    private javax.swing.JRadioButton s18;
    private javax.swing.JRadioButton th17;
    private javax.swing.JRadioButton th18;
    // End of variables declaration//GEN-END:variables
}
