/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package summercourse.Fweek;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import summercourse.javaMail;
public class FweekExampage11 extends javax.swing.JFrame {

    /**
     * Creates new form FweekExampage11
     */
    public FweekExampage11() {
        initComponents();
        ImageIcon i_mica= new ImageIcon("icons8-python-20.png");
        this.setIconImage(i_mica.getImage());
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader     fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                ResultSet     rs  = s.executeQuery("Select Q21 , Q22 from fweek_questions where id="+n+"");
                while(rs.next()){
                    String Q21= rs.getString("Q21");
                    String Q22= rs.getString("Q22");
                    if(Q21.equals("To perform mathematical calculations")){
                        f21.setSelected(true);
                        s21.setSelected(false);
                        th21.setSelected(false);
                }else if (Q21.equals("To generate random numbers")){
                        s21.setSelected(true);
                        f21.setSelected(false);
                        th21.setSelected(false);
                }else if (Q21.equals("To manipulate strings")){
                        th21.setSelected(true);
                        f21.setSelected(false);
                        s21.setSelected(false);
                }
                    if(Q22.equals("To repeat a set of instructions")){
                        f22.setSelected(true);
                        s22.setSelected(false);
                        th22.setSelected(false);
                }else if (Q22.equals("To make decisions based on conditions")){
                        s22.setSelected(true);
                        f22.setSelected(false);
                        th22.setSelected(false);
                }else if (Q22.equals("To perform mathematical calculations")){
                        th22.setSelected(true);
                        f22.setSelected(false);
                        s22.setSelected(false);
                }
                }}}catch(Exception e){
                }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        s21 = new javax.swing.JRadioButton();
        th21 = new javax.swing.JRadioButton();
        th22 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        s22 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        f21 = new javax.swing.JRadioButton();
        f22 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(39, 50, 56));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(39, 50, 56), 1, true));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("<<< Choose >>>");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(370, 10, 160, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 50, 56));
        jLabel2.setText("21-What is the purpose of the Math.random() function ?");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(19, 62, 630, 21);

        jPanel2.setBackground(new java.awt.Color(250, 250, 250));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(null);

        s21.setBackground(new java.awt.Color(250, 250, 250));
        s21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s21.setForeground(new java.awt.Color(39, 50, 56));
        s21.setText("To generate random numbers");
        s21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s21ActionPerformed(evt);
            }
        });
        jPanel2.add(s21);
        s21.setBounds(20, 90, 250, 23);

        th21.setBackground(new java.awt.Color(250, 250, 250));
        th21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        th21.setForeground(new java.awt.Color(39, 50, 56));
        th21.setText("To manipulate strings");
        th21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th21ActionPerformed(evt);
            }
        });
        jPanel2.add(th21);
        th21.setBounds(20, 120, 230, 23);

        th22.setBackground(new java.awt.Color(250, 250, 250));
        th22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        th22.setForeground(new java.awt.Color(39, 50, 56));
        th22.setText("To perform mathematical calculations");
        th22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                th22ActionPerformed(evt);
            }
        });
        jPanel2.add(th22);
        th22.setBounds(20, 300, 290, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 50, 56));
        jLabel3.setText("22-What is the purpose of an if statement in programming?");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 190, 680, 21);

        s22.setBackground(new java.awt.Color(250, 250, 250));
        s22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        s22.setForeground(new java.awt.Color(39, 50, 56));
        s22.setText("To make decisions based on conditions");
        s22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                s22ActionPerformed(evt);
            }
        });
        jPanel2.add(s22);
        s22.setBounds(20, 270, 280, 23);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-64.png"))); // NOI18N
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4);
        jLabel4.setBounds(820, 350, 60, 50);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-back-64__.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 350, 50, 50);

        f21.setBackground(new java.awt.Color(250, 250, 250));
        f21.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f21.setForeground(new java.awt.Color(39, 50, 56));
        f21.setText("To perform mathematical calculations");
        f21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f21ActionPerformed(evt);
            }
        });
        jPanel2.add(f21);
        f21.setBounds(20, 60, 310, 23);

        f22.setBackground(new java.awt.Color(250, 250, 250));
        f22.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        f22.setForeground(new java.awt.Color(39, 50, 56));
        f22.setText("To repeat a set of instructions");
        f22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f22ActionPerformed(evt);
            }
        });
        jPanel2.add(f22);
        f22.setBounds(20, 240, 240, 23);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 50, 890, 410);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void s21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s21ActionPerformed
        s21.setSelected(true);
        f21.setSelected(false);
        th21.setSelected(false);
    }//GEN-LAST:event_s21ActionPerformed

    private void th21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th21ActionPerformed
        th21.setSelected(true);
        f21.setSelected(false);
        s21.setSelected(false);
    }//GEN-LAST:event_th21ActionPerformed

    private void th22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_th22ActionPerformed
        th22.setSelected(true);
        f22.setSelected(false);
        s22.setSelected(false);
    }//GEN-LAST:event_th22ActionPerformed

    private void s22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_s22ActionPerformed
        s22.setSelected(true);
        f22.setSelected(false);
        th22.setSelected(false);
    }//GEN-LAST:event_s22ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            File           file21 = new File("ID\\Q21.txt");
            FileWriter     fw21 = new FileWriter(file21);
            BufferedWriter bw21 = new BufferedWriter(fw21);
            File           file22 = new File("ID\\Q22.txt");
            FileWriter     fw22 = new FileWriter(file22);
            BufferedWriter bw22 = new BufferedWriter(fw22);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                if(f21.isSelected()){
                    bw21.write("To perform mathematical calculations");
                    boolean     x  = s.execute("update fweek_questions set Q21='To perform mathematical calculations' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(s21.isSelected()){
                    bw21.write("To generate random numbers");
                    boolean     x2  = s.execute("update fweek_questions set Q21='To generate random numbers' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(th21.isSelected()){
                    bw21.write("To manipulate strings");
                    boolean     x21  = s.execute("update fweek_questions set Q21='To manipulate strings' where id="+n+"");
                    boolean       done = s.execute("commit");
                }
                bw21.close();
                fw21.close();
                if(f22.isSelected()){
                    bw22.write("To repeat a set of instructions");
                    boolean     x  = s.execute("update fweek_questions set Q22='To repeat a set of instructions' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(s22.isSelected()){
                    bw22.write("To make decisions based on conditions");
                    boolean     x2  = s.execute("update fweek_questions set Q22='To make decisions based on conditions' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(th22.isSelected()){
                    bw22.write("To perform mathematical calculations");
                    boolean     x3  = s.execute("update fweek_questions set Q22='To perform mathematical calculations' where id="+n+"");
                    boolean       done = s.execute("commit");
                }
                bw22.close();
                fw22.close();
            }
            boolean done = s.execute("commit");
            s.close();
            c.close();
            new FweekExampage12().setVisible(true);
            dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        Connection      c = null;
        Statement       s = null;
        try {
            String       file = "ID\\login.txt";
            c = new javaMail().connect();
            s = c.createStatement();
            FileReader fr = new javaMail().fileReader(file);
            BufferedReader br = new javaMail().bufferedReader(fr);
            File           file21 = new File("ID\\Q21.txt");
            FileWriter     fw21 = new FileWriter(file21);
            BufferedWriter bw21 = new BufferedWriter(fw21);
            File           file22 = new File("ID\\Q22.txt");
            FileWriter     fw22 = new FileWriter(file22);
            BufferedWriter bw22 = new BufferedWriter(fw22);
            int number;
            while ((number = fr.read()) != -1) {
                char n=(char)number;
                System.out.println(n);
                if(f21.isSelected()){
                    bw21.write("To perform mathematical calculations");
                    boolean     x  = s.execute("update fweek_questions set Q21='To perform mathematical calculations' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(s21.isSelected()){
                    bw21.write("To generate random numbers");
                    boolean     x2  = s.execute("update fweek_questions set Q21='To generate random numbers' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(th21.isSelected()){
                    bw21.write("To manipulate strings");
                    boolean     x21  = s.execute("update fweek_questions set Q21='To manipulate strings' where id="+n+"");
                    boolean       done = s.execute("commit");
                }
                bw21.close();
                fw21.close();
                if(f22.isSelected()){
                    bw22.write("To repeat a set of instructions");
                    boolean     x  = s.execute("update fweek_questions set Q22='To repeat a set of instructions' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(s22.isSelected()){
                    bw22.write("To make decisions based on conditions");
                    boolean     x2  = s.execute("update fweek_questions set Q22='To make decisions based on conditions' where id="+n+"");
                    boolean       done = s.execute("commit");
                }else if(th22.isSelected()){
                    bw22.write("To perform mathematical calculations");
                    boolean     x3  = s.execute("update fweek_questions set Q22='To perform mathematical calculations' where id="+n+"");
                    boolean       done = s.execute("commit");
                }
                bw22.close();
                fw22.close();
            }
            boolean done = s.execute("commit");
            s.close();
            c.close();
            new FweekExampage10().setVisible(true);
            dispose();

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }finally{
            try {
                s.close();
                c.close();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }       
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void f21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f21ActionPerformed
        f21.setSelected(true);
        s21.setSelected(false);
        th21.setSelected(false);
    }//GEN-LAST:event_f21ActionPerformed

    private void f22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f22ActionPerformed
        f22.setSelected(true);
        s22.setSelected(false);
        th22.setSelected(false);
    }//GEN-LAST:event_f22ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FweekExampage11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FweekExampage11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FweekExampage11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FweekExampage11.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FweekExampage11().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JRadioButton f21;
    public javax.swing.JRadioButton f22;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JRadioButton s21;
    public javax.swing.JRadioButton s22;
    public javax.swing.JRadioButton th21;
    public javax.swing.JRadioButton th22;
    // End of variables declaration//GEN-END:variables
}
